# CodeTraceBench preview notebook

This notebook loads the public **NJU-LINK/CodeTraceBench** dataset from Hugging Face and previews several first trajectories from the curated `verified` split.

**Source**  
The dataset card documents:
- `load_dataset("NJU-LINK/CodeTraceBench", split="verified")`
- a curated **verified** split with **1,000** trajectories and a **full** split with **3,316** trajectories
- fields such as `traj_id`, `agent`, `model`, `difficulty`, `category`, `step_count`, `stages`, and `incorrect_stages`. citeturn836420view1

In [ ]:
!pip -q install datasets pandas

In [1]:
import json
import ast
from pathlib import Path
from typing import Any
import pandas as pd
from IPython.display import display, Markdown

pd.set_option("display.max_colwidth", 200)

def truncate(text: Any, n: int = 300) -> str:
    if text is None:
        return ""
    s = str(text)
    return s if len(s) <= n else s[:n] + " …"

def maybe_parse_json(x: Any):
    if isinstance(x, (dict, list)):
        return x
    if not isinstance(x, str):
        return x
    x = x.strip()
    if not x:
        return x
    for fn in (json.loads, ast.literal_eval):
        try:
            return fn(x)
        except Exception:
            pass
    return x

def first_dialogue_excerpt(obj: Any, max_items: int = 4) -> str:
    parsed = maybe_parse_json(obj)
    if isinstance(parsed, list):
        parts = []
        for item in parsed[:max_items]:
            if isinstance(item, dict):
                role = item.get("role") or item.get("userType") or item.get("type") or "item"
                content = item.get("content") or item.get("text") or item.get("message") or item.get("action") or item.get("thought") or item
                parts.append(f"{role}: {truncate(content, 180)}")
            else:
                parts.append(truncate(item, 180))
        return "\n".join(parts)
    if isinstance(parsed, dict):
        return truncate(json.dumps(parsed, indent=2), 500)
    return truncate(parsed, 500)

def choose_first_existing(columns, candidates):
    for c in candidates:
        if c in columns:
            return c
    return None

In [2]:
from datasets import load_dataset

ds = load_dataset("NJU-LINK/CodeTraceBench", split="verified")
df = ds.to_pandas()
print(df.shape)
display(df.head())

README.md: 0.00B [00:00, ?B/s]

bench_manifest.full.parquet:   0%|          | 0.00/10.8M [00:00<?, ?B/s]

bench_manifest.verified.parquet:   0%|          | 0.00/984k [00:00<?, ?B/s]

Generating full split:   0%|          | 0/3316 [00:00<?, ? examples/s]

Generating verified split:   0%|          | 0/1000 [00:00<?, ? examples/s]

(1000, 19)

,traj_id,agent,model,task_name,task_slug,difficulty,category,tags,solved,step_count,stages,stage_count,incorrect_error_stage_count,trial_name,source_relpath,annotation_relpath,incorrect_stages,generated_at,artifact_path
0,miniswe-OpenAI__GPT-5-clap-rs__clap-2501-1c7ee8f3,mini-SWE-agent,OpenAI/GPT-5,clap-rs__clap-2501,clap-rs__clap-2501-1c7ee8f3,hard,software-engineering,[],True,25,"[{'end_step_id': 5, 'stage_id': 1, 'start_step_id': 1}, {'end_step_id': 10, 'stage_id': 2, 'start_step_id': 6}, {'end_step_id': 22, 'stage_id': 3, 'start_step_id': 11}, {'end_step_id': 23, 'stage_...",5,1,clap-rs__clap-2501,swe_raw/mini_swe_agent__multi/clap-rs__clap-2501,merged_cleaned_step25/mini_swe_agent__multi/clap-rs__clap-2501,"[{'incorrect_step_ids': [24], 'stage_id': 5, 'steps': [{'action_ref': None, 'labels': array(['incorrect'], dtype=object), 'observation_ref': None, 'step_id': 24}], 'unuseful_step_ids': []}]",2026-03-05T00:33:27+00:00,bench_artifacts/full/miniswe-OpenAI__GPT-5-clap-rs__clap-2501-1c7ee8f3.tar.zst
1,miniswe-OpenAI__GPT-5-clap-rs__clap-2758-8f87bc0d,mini-SWE-agent,OpenAI/GPT-5,clap-rs__clap-2758,clap-rs__clap-2758-8f87bc0d,hard,software-engineering,[],True,41,"[{'end_step_id': 4, 'stage_id': 1, 'start_step_id': 1}, {'end_step_id': 23, 'stage_id': 2, 'start_step_id': 5}, {'end_step_id': 29, 'stage_id': 3, 'start_step_id': 24}, {'end_step_id': 41, 'stage_...",4,0,clap-rs__clap-2758,swe_raw/mini_swe_agent__multi/clap-rs__clap-2758,merged_cleaned_step25/mini_swe_agent__multi/clap-rs__clap-2758,[],2026-03-05T00:33:27+00:00,bench_artifacts/full/miniswe-OpenAI__GPT-5-clap-rs__clap-2758-8f87bc0d.tar.zst
2,miniswe-OpenAI__GPT-5-clap-rs__clap-3179-107b6c1d,mini-SWE-agent,OpenAI/GPT-5,clap-rs__clap-3179,clap-rs__clap-3179-107b6c1d,hard,software-engineering,[],True,37,"[{'end_step_id': 5, 'stage_id': 1, 'start_step_id': 1}, {'end_step_id': 12, 'stage_id': 2, 'start_step_id': 6}, {'end_step_id': 16, 'stage_id': 3, 'start_step_id': 13}, {'end_step_id': 25, 'stage_...",7,2,clap-rs__clap-3179,swe_raw/mini_swe_agent__multi/clap-rs__clap-3179,merged_cleaned_step25/mini_swe_agent__multi/clap-rs__clap-3179,"[{'incorrect_step_ids': [33, 35], 'stage_id': 6, 'steps': [{'action_ref': None, 'labels': array(['incorrect'], dtype=object), 'observation_ref': None, 'step_id': 33}, {'action_ref': None, 'labels'...",2026-03-05T00:33:27+00:00,bench_artifacts/full/miniswe-OpenAI__GPT-5-clap-rs__clap-3179-107b6c1d.tar.zst
3,miniswe-OpenAI__GPT-5-clap-rs__clap-3421-8c92021d,mini-SWE-agent,OpenAI/GPT-5,clap-rs__clap-3421,clap-rs__clap-3421-8c92021d,medium,software-engineering,[],True,35,"[{'end_step_id': 5, 'stage_id': 1, 'start_step_id': 1}, {'end_step_id': 12, 'stage_id': 2, 'start_step_id': 6}, {'end_step_id': 22, 'stage_id': 3, 'start_step_id': 13}, {'end_step_id': 29, 'stage_...",6,2,clap-rs__clap-3421,swe_raw/mini_swe_agent__multi/clap-rs__clap-3421,merged_cleaned_step25/mini_swe_agent__multi/clap-rs__clap-3421,"[{'incorrect_step_ids': [23, 24, 25, 27, 28, 29], 'stage_id': 4, 'steps': [{'action_ref': None, 'labels': array(['incorrect'], dtype=object), 'observation_ref': None, 'step_id': 23}, {'action_ref'...",2026-03-05T00:33:27+00:00,bench_artifacts/full/miniswe-OpenAI__GPT-5-clap-rs__clap-3421-8c92021d.tar.zst
4,miniswe-OpenAI__GPT-5-clap-rs__clap-3975-5f1af46d,mini-SWE-agent,OpenAI/GPT-5,clap-rs__clap-3975,clap-rs__clap-3975-5f1af46d,hard,software-engineering,[],True,40,"[{'end_step_id': 6, 'stage_id': 1, 'start_step_id': 1}, {'end_step_id': 24, 'stage_id': 2, 'start_step_id': 7}, {'end_step_id': 32, 'stage_id': 3, 'start_step_id': 25}, {'end_step_id': 38, 'stage_...",5,2,clap-rs__clap-3975,swe_raw/mini_swe_agent__multi/clap-rs__clap-3975,merged_cleaned_step25/mini_swe_agent__multi/clap-rs__clap-3975,"[{'incorrect_step_ids': [33, 34, 35], 'stage_id': 4, 'steps': [{'action_ref': None, 'labels': array(['incorrect'], dtype=object), 'observation_ref': None, 'step_id': 33}, {'action_ref': None, 'lab...",2026-03-05T00:33:27+00:00,bench_artifacts/full/miniswe-OpenAI__GPT-5-clap-rs__clap-3975-5f1af46d.tar.zst

In [3]:
core_cols = [
    c for c in [
        "traj_id", "agent", "model", "task_name", "difficulty",
        "category", "solved", "step_count", "stage_count"
    ] if c in df.columns
]
display(df[core_cols].head(10))

,traj_id,agent,model,task_name,difficulty,category,solved,step_count,stage_count
0,miniswe-OpenAI__GPT-5-clap-rs__clap-2501-1c7ee8f3,mini-SWE-agent,OpenAI/GPT-5,clap-rs__clap-2501,hard,software-engineering,True,25,5
1,miniswe-OpenAI__GPT-5-clap-rs__clap-2758-8f87bc0d,mini-SWE-agent,OpenAI/GPT-5,clap-rs__clap-2758,hard,software-engineering,True,41,4
2,miniswe-OpenAI__GPT-5-clap-rs__clap-3179-107b6c1d,mini-SWE-agent,OpenAI/GPT-5,clap-rs__clap-3179,hard,software-engineering,True,37,7
3,miniswe-OpenAI__GPT-5-clap-rs__clap-3421-8c92021d,mini-SWE-agent,OpenAI/GPT-5,clap-rs__clap-3421,medium,software-engineering,True,35,6
4,miniswe-OpenAI__GPT-5-clap-rs__clap-3975-5f1af46d,mini-SWE-agent,OpenAI/GPT-5,clap-rs__clap-3975,hard,software-engineering,True,40,5
5,miniswe-OpenAI__GPT-5-clap-rs__clap-4248-85bd7a43,mini-SWE-agent,OpenAI/GPT-5,clap-rs__clap-4248,hard,software-engineering,True,35,4
6,miniswe-OpenAI__GPT-5-facebook__zstd-1733-786102c1,mini-SWE-agent,OpenAI/GPT-5,facebook__zstd-1733,hard,software-engineering,True,44,6
7,miniswe-OpenAI__GPT-5-facebook__zstd-2094-7f31a0cb,mini-SWE-agent,OpenAI/GPT-5,facebook__zstd-2094,hard,software-engineering,True,28,3
8,miniswe-OpenAI__GPT-5-nushell__nushell-13357-4bd10bdc,mini-SWE-agent,OpenAI/GPT-5,nushell__nushell-13357,hard,software-engineering,True,31,6
9,miniswe-OpenAI__GPT-5-ponylang__ponyc-1057-56b583ae,mini-SWE-agent,OpenAI/GPT-5,ponylang__ponyc-1057,hard,software-engineering,True,57,8

In [4]:
examples = []
for _, row in df.head(5).iterrows():
    stages = maybe_parse_json(row.get("stages"))
    incorrect = maybe_parse_json(row.get("incorrect_stages"))
    examples.append({
        "traj_id": row.get("traj_id"),
        "agent": row.get("agent"),
        "model": row.get("model"),
        "task_name": row.get("task_name"),
        "difficulty": row.get("difficulty"),
        "solved": row.get("solved"),
        "step_count": row.get("step_count"),
        "num_stages": len(stages) if isinstance(stages, list) else None,
        "num_annotated_incorrect_stages": len(incorrect) if isinstance(incorrect, list) else None,
        "stages_excerpt": truncate(stages, 250),
        "incorrect_excerpt": truncate(incorrect, 250),
    })
example_df = pd.DataFrame(examples)
display(example_df)

,traj_id,agent,model,task_name,difficulty,solved,step_count,num_stages,num_annotated_incorrect_stages,stages_excerpt,incorrect_excerpt
0,miniswe-OpenAI__GPT-5-clap-rs__clap-2501-1c7ee8f3,mini-SWE-agent,OpenAI/GPT-5,clap-rs__clap-2501,hard,True,25,None,None,"[{'end_step_id': 5, 'stage_id': 1, 'start_step_id': 1}\n {'end_step_id': 10, 'stage_id': 2, 'start_step_id': 6}\n {'end_step_id': 22, 'stage_id': 3, 'start_step_id': 11}\n {'end_step_id': 23, 'sta...","[{'incorrect_step_ids': array([24]), 'stage_id': 5, 'steps': array([{'action_ref': None, 'labels': array(['incorrect'], dtype=object), 'observation_ref': None, 'step_id': 24}],\n dtype=objec..."
1,miniswe-OpenAI__GPT-5-clap-rs__clap-2758-8f87bc0d,mini-SWE-agent,OpenAI/GPT-5,clap-rs__clap-2758,hard,True,41,None,None,"[{'end_step_id': 4, 'stage_id': 1, 'start_step_id': 1}\n {'end_step_id': 23, 'stage_id': 2, 'start_step_id': 5}\n {'end_step_id': 29, 'stage_id': 3, 'start_step_id': 24}\n {'end_step_id': 41, 'sta...",[]
2,miniswe-OpenAI__GPT-5-clap-rs__clap-3179-107b6c1d,mini-SWE-agent,OpenAI/GPT-5,clap-rs__clap-3179,hard,True,37,None,None,"[{'end_step_id': 5, 'stage_id': 1, 'start_step_id': 1}\n {'end_step_id': 12, 'stage_id': 2, 'start_step_id': 6}\n {'end_step_id': 16, 'stage_id': 3, 'start_step_id': 13}\n {'end_step_id': 25, 'sta...","[{'incorrect_step_ids': array([33, 35]), 'stage_id': 6, 'steps': array([{'action_ref': None, 'labels': array(['incorrect'], dtype=object), 'observation_ref': None, 'step_id': 33},\n {'actio..."
3,miniswe-OpenAI__GPT-5-clap-rs__clap-3421-8c92021d,mini-SWE-agent,OpenAI/GPT-5,clap-rs__clap-3421,medium,True,35,None,None,"[{'end_step_id': 5, 'stage_id': 1, 'start_step_id': 1}\n {'end_step_id': 12, 'stage_id': 2, 'start_step_id': 6}\n {'end_step_id': 22, 'stage_id': 3, 'start_step_id': 13}\n {'end_step_id': 29, 'sta...","[{'incorrect_step_ids': array([23, 24, 25, 27, 28, 29]), 'stage_id': 4, 'steps': array([{'action_ref': None, 'labels': array(['incorrect'], dtype=object), 'observation_ref': None, 'step_id': 23},\..."
4,miniswe-OpenAI__GPT-5-clap-rs__clap-3975-5f1af46d,mini-SWE-agent,OpenAI/GPT-5,clap-rs__clap-3975,hard,True,40,None,None,"[{'end_step_id': 6, 'stage_id': 1, 'start_step_id': 1}\n {'end_step_id': 24, 'stage_id': 2, 'start_step_id': 7}\n {'end_step_id': 32, 'stage_id': 3, 'start_step_id': 25}\n {'end_step_id': 38, 'sta...","[{'incorrect_step_ids': array([33, 34, 35]), 'stage_id': 4, 'steps': array([{'action_ref': None, 'labels': array(['incorrect'], dtype=object), 'observation_ref': None, 'step_id': 33},\n {'a..."

In [5]:
if "category" in df.columns:
    display(df["category"].value_counts().head(20).rename_axis("category").reset_index(name="count"))
if "agent" in df.columns:
    display(df["agent"].value_counts().rename_axis("agent").reset_index(name="count"))

                 category  count
0    software-engineering    605
1   system-administration     65
2    scientific-computing     43
3            data-science     40
4               debugging     39
5          model-training     35
6                security     32
7         file-operations     30
8             mathematics     27
9        machine-learning     24
10                  games     15
11             algorithms      8
12        data-processing      8
13    reproducible-builds      4
14                   game      4
15     personal-assistant      3
16        computer-vision      3
17           optimization      3
18       audio-processing      3
19            file-system      2

            agent  count
0       OpenHands    520
1       Terminus2    222
2  mini-SWE-agent    150
3       SWE-agent    108